### ISSUE TITLE
SEO Feedback und Optimierungsvorschläge zum Blog

### ISSUE THREAD

**Issue by follmann** [trsc/kittysplit-blog#8]
Nachdem dem Release vom Unequal Splti Feature ist meine Freundin auch auf den Blogpost dazu gestossen und hat mir daraufhin untenstehendes Feedback gegeben. Vielleicht können wir das ja noch einarbeiten und/oder zukünftig nutzen?

(Hintergrund: SIe hat einige Erfahrung im Bereich Aufbauen und Optimieren von Blogs und Onlinemagazinen)

--

Das sind die monatlichen Suchanfragen in dem Themenbereich:

Unequal splitting: 0 
Cost Split: 4.400
Split the bills: 9.900
Kittysplit: 2400 (YEAAH!)
Split App: 2000
Money Sharing App: 1300
Split Expenses: 1300
Group Payment App: 260

Da Unequal Splitting 0 Suchanfragen hat, wird Google den Blogartikel nie finden. Mein Vorschlag: Du steckst mal das Keyword Cost Split in die Headline ("Cost Split: Go unequal", z.B.), fügst noch ein weiteres Bild ein, legst Zwischenüberschriften an und packst das Keyword Cost Split in den Alt Tag von den Bildern. Am besten auch etwas Text ergänzen, dass du auf 300 Wörter kommst, das ist das Minimum von Google. Und ganz wichtig: Wenn ich von Google kommend den Beitrag lese und denke: "Ja cool, will ich nutzen", fehlt mir am Ende eine Weiterleitung zum Produkt. Also ein Call-To-Action "Use Kittysplit now" und dann direkter Link auf Kittysplit. Nur so als Tipps.

Und Wahnsinn, dass Kittysplit als Marke schon 2400 Suchanfragen monatlich hat. Das ist super!

Und am besten für die Artikel-Optimierung auch die URL umbenennen: http://blog.kittysplit.com/cost-split. Falls Ihr den blogpost schon promotet habt, könntet ihr ne Weiterleitung auf die neue URL einrichten

**Comment by caspii** [comment]
Wow, cool. Ich kümmer mich drum
